// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module srcnn_load_tile_mm (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_gmem_in_AWVALID,
        m_axi_gmem_in_AWREADY,
        m_axi_gmem_in_AWADDR,
        m_axi_gmem_in_AWID,
        m_axi_gmem_in_AWLEN,
        m_axi_gmem_in_AWSIZE,
        m_axi_gmem_in_AWBURST,
        m_axi_gmem_in_AWLOCK,
        m_axi_gmem_in_AWCACHE,
        m_axi_gmem_in_AWPROT,
        m_axi_gmem_in_AWQOS,
        m_axi_gmem_in_AWREGION,
        m_axi_gmem_in_AWUSER,
        m_axi_gmem_in_WVALID,
        m_axi_gmem_in_WREADY,
        m_axi_gmem_in_WDATA,
        m_axi_gmem_in_WSTRB,
        m_axi_gmem_in_WLAST,
        m_axi_gmem_in_WID,
        m_axi_gmem_in_WUSER,
        m_axi_gmem_in_ARVALID,
        m_axi_gmem_in_ARREADY,
        m_axi_gmem_in_ARADDR,
        m_axi_gmem_in_ARID,
        m_axi_gmem_in_ARLEN,
        m_axi_gmem_in_ARSIZE,
        m_axi_gmem_in_ARBURST,
        m_axi_gmem_in_ARLOCK,
        m_axi_gmem_in_ARCACHE,
        m_axi_gmem_in_ARPROT,
        m_axi_gmem_in_ARQOS,
        m_axi_gmem_in_ARREGION,
        m_axi_gmem_in_ARUSER,
        m_axi_gmem_in_RVALID,
        m_axi_gmem_in_RREADY,
        m_axi_gmem_in_RDATA,
        m_axi_gmem_in_RLAST,
        m_axi_gmem_in_RID,
        m_axi_gmem_in_RFIFONUM,
        m_axi_gmem_in_RUSER,
        m_axi_gmem_in_RRESP,
        m_axi_gmem_in_BVALID,
        m_axi_gmem_in_BREADY,
        m_axi_gmem_in_BRESP,
        m_axi_gmem_in_BID,
        m_axi_gmem_in_BUSER,
        input_ftmap,
        h0,
        w0,
        phase,
        inbuf_address0,
        inbuf_ce0,
        inbuf_we0,
        inbuf_d0,
        ap_return_0,
        ap_return_1,
        ap_return_2
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_in_AWVALID;
input   m_axi_gmem_in_AWREADY;
output  [63:0] m_axi_gmem_in_AWADDR;
output  [0:0] m_axi_gmem_in_AWID;
output  [31:0] m_axi_gmem_in_AWLEN;
output  [2:0] m_axi_gmem_in_AWSIZE;
output  [1:0] m_axi_gmem_in_AWBURST;
output  [1:0] m_axi_gmem_in_AWLOCK;
output  [3:0] m_axi_gmem_in_AWCACHE;
output  [2:0] m_axi_gmem_in_AWPROT;
output  [3:0] m_axi_gmem_in_AWQOS;
output  [3:0] m_axi_gmem_in_AWREGION;
output  [0:0] m_axi_gmem_in_AWUSER;
output   m_axi_gmem_in_WVALID;
input   m_axi_gmem_in_WREADY;
output  [31:0] m_axi_gmem_in_WDATA;
output  [3:0] m_axi_gmem_in_WSTRB;
output   m_axi_gmem_in_WLAST;
output  [0:0] m_axi_gmem_in_WID;
output  [0:0] m_axi_gmem_in_WUSER;
output   m_axi_gmem_in_ARVALID;
input   m_axi_gmem_in_ARREADY;
output  [63:0] m_axi_gmem_in_ARADDR;
output  [0:0] m_axi_gmem_in_ARID;
output  [31:0] m_axi_gmem_in_ARLEN;
output  [2:0] m_axi_gmem_in_ARSIZE;
output  [1:0] m_axi_gmem_in_ARBURST;
output  [1:0] m_axi_gmem_in_ARLOCK;
output  [3:0] m_axi_gmem_in_ARCACHE;
output  [2:0] m_axi_gmem_in_ARPROT;
output  [3:0] m_axi_gmem_in_ARQOS;
output  [3:0] m_axi_gmem_in_ARREGION;
output  [0:0] m_axi_gmem_in_ARUSER;
input   m_axi_gmem_in_RVALID;
output   m_axi_gmem_in_RREADY;
input  [31:0] m_axi_gmem_in_RDATA;
input   m_axi_gmem_in_RLAST;
input  [0:0] m_axi_gmem_in_RID;
input  [8:0] m_axi_gmem_in_RFIFONUM;
input  [0:0] m_axi_gmem_in_RUSER;
input  [1:0] m_axi_gmem_in_RRESP;
input   m_axi_gmem_in_BVALID;
output   m_axi_gmem_in_BREADY;
input  [1:0] m_axi_gmem_in_BRESP;
input  [0:0] m_axi_gmem_in_BID;
input  [0:0] m_axi_gmem_in_BUSER;
input  [63:0] input_ftmap;
input  [8:0] h0;
input  [7:0] w0;
input  [0:0] phase;
output  [10:0] inbuf_address0;
output   inbuf_ce0;
output   inbuf_we0;
output  [31:0] inbuf_d0;
output  [8:0] ap_return_0;
output  [8:0] ap_return_1;
output  [0:0] ap_return_2;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem_in_ARVALID;
reg m_axi_gmem_in_RREADY;
reg[8:0] ap_return_0;
reg[8:0] ap_return_1;
reg[0:0] ap_return_2;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1;
wire   [8:0] w0_cast2_fu_111_p1;
reg   [8:0] w0_cast2_reg_250;
wire   [8:0] add_ln40_fu_179_p2;
reg   [8:0] add_ln40_reg_256;
wire    ap_CS_fsm_state4;
wire   [2:0] select_ln53_fu_193_p3;
reg   [2:0] select_ln53_reg_276;
wire   [9:0] add_ln44_fu_205_p2;
reg   [9:0] add_ln44_reg_281;
wire   [8:0] add_ln50_fu_213_p2;
reg   [8:0] add_ln50_reg_287;
wire  signed [16:0] grp_fu_235_p3;
reg   [16:0] mul_ln44_reg_293;
wire    grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_start;
wire    grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_done;
wire    grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_idle;
wire    grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_ready;
wire    grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWVALID;
wire   [63:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWADDR;
wire   [0:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWID;
wire   [31:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWLEN;
wire   [2:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWSIZE;
wire   [1:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWBURST;
wire   [1:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWLOCK;
wire   [3:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWCACHE;
wire   [2:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWPROT;
wire   [3:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWQOS;
wire   [3:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWREGION;
wire   [0:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWUSER;
wire    grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_WVALID;
wire   [31:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_WDATA;
wire   [3:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_WSTRB;
wire    grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_WLAST;
wire   [0:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_WID;
wire   [0:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_WUSER;
wire    grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARVALID;
wire   [63:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARADDR;
wire   [0:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARID;
wire   [31:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARLEN;
wire   [2:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARSIZE;
wire   [1:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARBURST;
wire   [1:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARLOCK;
wire   [3:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARCACHE;
wire   [2:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARPROT;
wire   [3:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARQOS;
wire   [3:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARREGION;
wire   [0:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARUSER;
wire    grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_RREADY;
wire    grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_BREADY;
wire   [10:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_inbuf_address0;
wire    grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_inbuf_ce0;
wire    grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_inbuf_we0;
wire   [31:0] grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_inbuf_d0;
reg    grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_start_reg;
wire    ap_CS_fsm_state5;
wire   [8:0] add_ln399_fu_115_p2;
wire   [7:0] trunc_ln398_fu_129_p1;
wire   [0:0] tmp_fu_121_p3;
wire   [7:0] xor_ln399_fu_133_p2;
wire   [8:0] add_ln401_fu_147_p2;
wire   [0:0] tmp_6_fu_153_p3;
wire   [7:0] xor_ln401_fu_161_p2;
wire   [7:0] tw_eff_fu_167_p3;
wire   [8:0] tw_eff_cast_fu_175_p1;
wire   [7:0] th_eff_fu_139_p3;
wire   [9:0] h0_cast11_i_fu_202_p1;
wire   [7:0] grp_fu_235_p0;
wire   [3:0] grp_fu_235_p1;
wire   [8:0] grp_fu_235_p2;
reg    grp_fu_235_ce;
reg   [8:0] ap_return_0_preg;
reg   [8:0] ap_return_1_preg;
reg   [0:0] ap_return_2_preg;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire   [8:0] grp_fu_235_p00;
wire   [16:0] grp_fu_235_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_start_reg = 1'b0;
#0 ap_return_0_preg = 9'd0;
#0 ap_return_1_preg = 9'd0;
#0 ap_return_2_preg = 1'd0;
end

srcnn_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2 grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_start),
    .ap_done(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_done),
    .ap_idle(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_idle),
    .ap_ready(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_ready),
    .m_axi_gmem_in_AWVALID(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWVALID),
    .m_axi_gmem_in_AWREADY(1'b0),
    .m_axi_gmem_in_AWADDR(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWADDR),
    .m_axi_gmem_in_AWID(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWID),
    .m_axi_gmem_in_AWLEN(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWLEN),
    .m_axi_gmem_in_AWSIZE(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWSIZE),
    .m_axi_gmem_in_AWBURST(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWBURST),
    .m_axi_gmem_in_AWLOCK(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWLOCK),
    .m_axi_gmem_in_AWCACHE(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWCACHE),
    .m_axi_gmem_in_AWPROT(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWPROT),
    .m_axi_gmem_in_AWQOS(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWQOS),
    .m_axi_gmem_in_AWREGION(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWREGION),
    .m_axi_gmem_in_AWUSER(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_AWUSER),
    .m_axi_gmem_in_WVALID(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_WVALID),
    .m_axi_gmem_in_WREADY(1'b0),
    .m_axi_gmem_in_WDATA(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_WDATA),
    .m_axi_gmem_in_WSTRB(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_WSTRB),
    .m_axi_gmem_in_WLAST(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_WLAST),
    .m_axi_gmem_in_WID(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_WID),
    .m_axi_gmem_in_WUSER(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_WUSER),
    .m_axi_gmem_in_ARVALID(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARVALID),
    .m_axi_gmem_in_ARREADY(m_axi_gmem_in_ARREADY),
    .m_axi_gmem_in_ARADDR(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARADDR),
    .m_axi_gmem_in_ARID(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARID),
    .m_axi_gmem_in_ARLEN(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARLEN),
    .m_axi_gmem_in_ARSIZE(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARSIZE),
    .m_axi_gmem_in_ARBURST(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARBURST),
    .m_axi_gmem_in_ARLOCK(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARLOCK),
    .m_axi_gmem_in_ARCACHE(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARCACHE),
    .m_axi_gmem_in_ARPROT(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARPROT),
    .m_axi_gmem_in_ARQOS(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARQOS),
    .m_axi_gmem_in_ARREGION(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARREGION),
    .m_axi_gmem_in_ARUSER(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARUSER),
    .m_axi_gmem_in_RVALID(m_axi_gmem_in_RVALID),
    .m_axi_gmem_in_RREADY(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_RREADY),
    .m_axi_gmem_in_RDATA(m_axi_gmem_in_RDATA),
    .m_axi_gmem_in_RLAST(m_axi_gmem_in_RLAST),
    .m_axi_gmem_in_RID(m_axi_gmem_in_RID),
    .m_axi_gmem_in_RFIFONUM(m_axi_gmem_in_RFIFONUM),
    .m_axi_gmem_in_RUSER(m_axi_gmem_in_RUSER),
    .m_axi_gmem_in_RRESP(m_axi_gmem_in_RRESP),
    .m_axi_gmem_in_BVALID(1'b0),
    .m_axi_gmem_in_BREADY(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_BREADY),
    .m_axi_gmem_in_BRESP(2'd0),
    .m_axi_gmem_in_BID(1'd0),
    .m_axi_gmem_in_BUSER(1'd0),
    .sext_ln44(add_ln44_reg_281),
    .add_ln44(add_ln44_reg_281),
    .bound(mul_ln44_reg_293),
    .add_ln40(add_ln40_reg_256),
    .select_ln53(select_ln53_reg_276),
    .sext_ln50(add_ln50_reg_287),
    .sext_ln50_1(add_ln50_reg_287),
    .input_ftmap(input_ftmap),
    .inbuf_address0(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_inbuf_address0),
    .inbuf_ce0(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_inbuf_ce0),
    .inbuf_we0(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_inbuf_we0),
    .inbuf_d0(grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_inbuf_d0)
);

srcnn_am_addmul_8ns_4ns_9ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 17 ))
am_addmul_8ns_4ns_9ns_17_4_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_235_p0),
    .din1(grp_fu_235_p1),
    .din2(grp_fu_235_p2),
    .ce(grp_fu_235_ce),
    .dout(grp_fu_235_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 9'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) & (grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_done == 1'b1))) begin
            ap_return_0_preg <= h0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_1_preg[0] <= 1'b0;
        ap_return_1_preg[1] <= 1'b0;
        ap_return_1_preg[2] <= 1'b0;
        ap_return_1_preg[3] <= 1'b0;
        ap_return_1_preg[4] <= 1'b0;
        ap_return_1_preg[5] <= 1'b0;
        ap_return_1_preg[6] <= 1'b0;
        ap_return_1_preg[7] <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) & (grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_done == 1'b1))) begin
                        ap_return_1_preg[7 : 0] <= w0_cast2_reg_250[7 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) & (grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_done == 1'b1))) begin
            ap_return_2_preg <= phase;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_start_reg <= 1'b1;
        end else if ((grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_ready == 1'b1)) begin
            grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln40_reg_256 <= add_ln40_fu_179_p2;
        w0_cast2_reg_250[7 : 0] <= w0_cast2_fu_111_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln44_reg_281 <= add_ln44_fu_205_p2;
        add_ln50_reg_287 <= add_ln50_fu_213_p2;
        mul_ln44_reg_293 <= grp_fu_235_p3;
        select_ln53_reg_276[2] <= select_ln53_fu_193_p3[2];
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_done == 1'b1))) begin
        ap_return_0 = h0;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_done == 1'b1))) begin
        ap_return_1 = w0_cast2_reg_250;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_done == 1'b1))) begin
        ap_return_2 = phase;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & ((ap_done_reg == 1'b1) | (ap_start == 1'b0))))) begin
        grp_fu_235_ce = 1'b0;
    end else begin
        grp_fu_235_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem_in_ARVALID = grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARVALID;
    end else begin
        m_axi_gmem_in_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem_in_RREADY = grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_RREADY;
    end else begin
        m_axi_gmem_in_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln399_fu_115_p2 = (h0 + 9'd16);

assign add_ln401_fu_147_p2 = (w0_cast2_fu_111_p1 + 9'd16);

assign add_ln40_fu_179_p2 = (tw_eff_cast_fu_175_p1 + 9'd12);

assign add_ln44_fu_205_p2 = ($signed(h0_cast11_i_fu_202_p1) + $signed(10'd1018));

assign add_ln50_fu_213_p2 = ($signed(w0_cast2_reg_250) + $signed(9'd506));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_fu_235_p0 = grp_fu_235_p00;

assign grp_fu_235_p00 = th_eff_fu_139_p3;

assign grp_fu_235_p1 = 9'd12;

assign grp_fu_235_p2 = grp_fu_235_p20;

assign grp_fu_235_p20 = add_ln40_fu_179_p2;

assign grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_start = grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_ap_start_reg;

assign h0_cast11_i_fu_202_p1 = h0;

assign inbuf_address0 = grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_inbuf_address0;

assign inbuf_ce0 = grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_inbuf_ce0;

assign inbuf_d0 = grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_inbuf_d0;

assign inbuf_we0 = grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_inbuf_we0;

assign m_axi_gmem_in_ARADDR = grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARADDR;

assign m_axi_gmem_in_ARBURST = grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARBURST;

assign m_axi_gmem_in_ARCACHE = grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARCACHE;

assign m_axi_gmem_in_ARID = grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARID;

assign m_axi_gmem_in_ARLEN = grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARLEN;

assign m_axi_gmem_in_ARLOCK = grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARLOCK;

assign m_axi_gmem_in_ARPROT = grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARPROT;

assign m_axi_gmem_in_ARQOS = grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARQOS;

assign m_axi_gmem_in_ARREGION = grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARREGION;

assign m_axi_gmem_in_ARSIZE = grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARSIZE;

assign m_axi_gmem_in_ARUSER = grp_load_tile_mm_Pipeline_VITIS_LOOP_40_1_VITIS_LOOP_48_2_fu_94_m_axi_gmem_in_ARUSER;

assign m_axi_gmem_in_AWADDR = 64'd0;

assign m_axi_gmem_in_AWBURST = 2'd0;

assign m_axi_gmem_in_AWCACHE = 4'd0;

assign m_axi_gmem_in_AWID = 1'd0;

assign m_axi_gmem_in_AWLEN = 32'd0;

assign m_axi_gmem_in_AWLOCK = 2'd0;

assign m_axi_gmem_in_AWPROT = 3'd0;

assign m_axi_gmem_in_AWQOS = 4'd0;

assign m_axi_gmem_in_AWREGION = 4'd0;

assign m_axi_gmem_in_AWSIZE = 3'd0;

assign m_axi_gmem_in_AWUSER = 1'd0;

assign m_axi_gmem_in_AWVALID = 1'b0;

assign m_axi_gmem_in_BREADY = 1'b0;

assign m_axi_gmem_in_WDATA = 32'd0;

assign m_axi_gmem_in_WID = 1'd0;

assign m_axi_gmem_in_WLAST = 1'b0;

assign m_axi_gmem_in_WSTRB = 4'd0;

assign m_axi_gmem_in_WUSER = 1'd0;

assign m_axi_gmem_in_WVALID = 1'b0;

assign select_ln53_fu_193_p3 = ((phase[0:0] == 1'b1) ? 3'd4 : 3'd0);

assign th_eff_fu_139_p3 = ((tmp_fu_121_p3[0:0] == 1'b1) ? xor_ln399_fu_133_p2 : 8'd16);

assign tmp_6_fu_153_p3 = add_ln401_fu_147_p2[32'd8];

assign tmp_fu_121_p3 = add_ln399_fu_115_p2[32'd8];

assign trunc_ln398_fu_129_p1 = h0[7:0];

assign tw_eff_cast_fu_175_p1 = tw_eff_fu_167_p3;

assign tw_eff_fu_167_p3 = ((tmp_6_fu_153_p3[0:0] == 1'b1) ? xor_ln401_fu_161_p2 : 8'd16);

assign w0_cast2_fu_111_p1 = w0;

assign xor_ln399_fu_133_p2 = (trunc_ln398_fu_129_p1 ^ 8'd255);

assign xor_ln401_fu_161_p2 = (w0 ^ 8'd255);

always @ (posedge ap_clk) begin
    w0_cast2_reg_250[8] <= 1'b0;
    select_ln53_reg_276[1:0] <= 2'b00;
    ap_return_1_preg[8] <= 1'b0;
end

endmodule //srcnn_load_tile_mm
