// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module srcnn_load_tile_mm (
        m_axi_gmem_in_AWVALID,
        m_axi_gmem_in_AWREADY,
        m_axi_gmem_in_AWADDR,
        m_axi_gmem_in_AWID,
        m_axi_gmem_in_AWLEN,
        m_axi_gmem_in_AWSIZE,
        m_axi_gmem_in_AWBURST,
        m_axi_gmem_in_AWLOCK,
        m_axi_gmem_in_AWCACHE,
        m_axi_gmem_in_AWPROT,
        m_axi_gmem_in_AWQOS,
        m_axi_gmem_in_AWREGION,
        m_axi_gmem_in_AWUSER,
        m_axi_gmem_in_WVALID,
        m_axi_gmem_in_WREADY,
        m_axi_gmem_in_WDATA,
        m_axi_gmem_in_WSTRB,
        m_axi_gmem_in_WLAST,
        m_axi_gmem_in_WID,
        m_axi_gmem_in_WUSER,
        m_axi_gmem_in_ARVALID,
        m_axi_gmem_in_ARREADY,
        m_axi_gmem_in_ARADDR,
        m_axi_gmem_in_ARID,
        m_axi_gmem_in_ARLEN,
        m_axi_gmem_in_ARSIZE,
        m_axi_gmem_in_ARBURST,
        m_axi_gmem_in_ARLOCK,
        m_axi_gmem_in_ARCACHE,
        m_axi_gmem_in_ARPROT,
        m_axi_gmem_in_ARQOS,
        m_axi_gmem_in_ARREGION,
        m_axi_gmem_in_ARUSER,
        m_axi_gmem_in_RVALID,
        m_axi_gmem_in_RREADY,
        m_axi_gmem_in_RDATA,
        m_axi_gmem_in_RLAST,
        m_axi_gmem_in_RID,
        m_axi_gmem_in_RFIFONUM,
        m_axi_gmem_in_RUSER,
        m_axi_gmem_in_RRESP,
        m_axi_gmem_in_BVALID,
        m_axi_gmem_in_BREADY,
        m_axi_gmem_in_BRESP,
        m_axi_gmem_in_BID,
        m_axi_gmem_in_BUSER,
        input_ftmap,
        h0,
        w0,
        phase,
        h0_c1_din,
        h0_c1_full_n,
        h0_c1_write,
        w0_c2_din,
        w0_c2_full_n,
        w0_c2_write,
        phase_c3_din,
        phase_c3_full_n,
        phase_c3_write,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_address0,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_ce0,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_d0,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_q0,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_we0,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_address0,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_ce0,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_d0,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_q0,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_we0,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_address0,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_ce0,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_d0,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_q0,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_we0,
        ap_clk,
        ap_rst,
        phase_ap_vld,
        w0_ap_vld,
        h0_ap_vld,
        ap_start,
        input_ftmap_ap_vld,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_full_n,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_write,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_full_n,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_write,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_full_n,
        srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_write,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output   m_axi_gmem_in_AWVALID;
input   m_axi_gmem_in_AWREADY;
output  [63:0] m_axi_gmem_in_AWADDR;
output  [0:0] m_axi_gmem_in_AWID;
output  [31:0] m_axi_gmem_in_AWLEN;
output  [2:0] m_axi_gmem_in_AWSIZE;
output  [1:0] m_axi_gmem_in_AWBURST;
output  [1:0] m_axi_gmem_in_AWLOCK;
output  [3:0] m_axi_gmem_in_AWCACHE;
output  [2:0] m_axi_gmem_in_AWPROT;
output  [3:0] m_axi_gmem_in_AWQOS;
output  [3:0] m_axi_gmem_in_AWREGION;
output  [0:0] m_axi_gmem_in_AWUSER;
output   m_axi_gmem_in_WVALID;
input   m_axi_gmem_in_WREADY;
output  [31:0] m_axi_gmem_in_WDATA;
output  [3:0] m_axi_gmem_in_WSTRB;
output   m_axi_gmem_in_WLAST;
output  [0:0] m_axi_gmem_in_WID;
output  [0:0] m_axi_gmem_in_WUSER;
output   m_axi_gmem_in_ARVALID;
input   m_axi_gmem_in_ARREADY;
output  [63:0] m_axi_gmem_in_ARADDR;
output  [0:0] m_axi_gmem_in_ARID;
output  [31:0] m_axi_gmem_in_ARLEN;
output  [2:0] m_axi_gmem_in_ARSIZE;
output  [1:0] m_axi_gmem_in_ARBURST;
output  [1:0] m_axi_gmem_in_ARLOCK;
output  [3:0] m_axi_gmem_in_ARCACHE;
output  [2:0] m_axi_gmem_in_ARPROT;
output  [3:0] m_axi_gmem_in_ARQOS;
output  [3:0] m_axi_gmem_in_ARREGION;
output  [0:0] m_axi_gmem_in_ARUSER;
input   m_axi_gmem_in_RVALID;
output   m_axi_gmem_in_RREADY;
input  [31:0] m_axi_gmem_in_RDATA;
input   m_axi_gmem_in_RLAST;
input  [0:0] m_axi_gmem_in_RID;
input  [8:0] m_axi_gmem_in_RFIFONUM;
input  [0:0] m_axi_gmem_in_RUSER;
input  [1:0] m_axi_gmem_in_RRESP;
input   m_axi_gmem_in_BVALID;
output   m_axi_gmem_in_BREADY;
input  [1:0] m_axi_gmem_in_BRESP;
input  [0:0] m_axi_gmem_in_BID;
input  [0:0] m_axi_gmem_in_BUSER;
input  [63:0] input_ftmap;
input  [8:0] h0;
input  [7:0] w0;
input  [0:0] phase;
output  [8:0] h0_c1_din;
input   h0_c1_full_n;
output   h0_c1_write;
output  [7:0] w0_c2_din;
input   w0_c2_full_n;
output   w0_c2_write;
output  [0:0] phase_c3_din;
input   phase_c3_full_n;
output   phase_c3_write;
output  [9:0] srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_address0;
output   srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_ce0;
output  [31:0] srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_d0;
input  [31:0] srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_q0;
output   srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_we0;
output  [9:0] srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_address0;
output   srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_ce0;
output  [31:0] srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_d0;
input  [31:0] srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_q0;
output   srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_we0;
output  [9:0] srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_address0;
output   srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_ce0;
output  [31:0] srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_d0;
input  [31:0] srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_q0;
output   srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_we0;
input   ap_clk;
input   ap_rst;
input   phase_ap_vld;
input   w0_ap_vld;
input   h0_ap_vld;
input   ap_start;
input   input_ftmap_ap_vld;
input   srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_full_n;
output   srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_write;
input   srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_full_n;
output   srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_write;
input   srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_full_n;
output   srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_write;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    load_tile_mm_Block_entry38_proc_U0_ap_start;
wire    load_tile_mm_Block_entry38_proc_U0_ap_done;
wire    load_tile_mm_Block_entry38_proc_U0_ap_continue;
wire    load_tile_mm_Block_entry38_proc_U0_ap_idle;
wire    load_tile_mm_Block_entry38_proc_U0_ap_ready;
wire   [8:0] load_tile_mm_Block_entry38_proc_U0_h0_c1_din;
wire    load_tile_mm_Block_entry38_proc_U0_h0_c1_write;
wire   [7:0] load_tile_mm_Block_entry38_proc_U0_w0_c2_din;
wire    load_tile_mm_Block_entry38_proc_U0_w0_c2_write;
wire   [0:0] load_tile_mm_Block_entry38_proc_U0_phase_c3_din;
wire    load_tile_mm_Block_entry38_proc_U0_phase_c3_write;
wire   [63:0] load_tile_mm_Block_entry38_proc_U0_ap_return_0;
wire   [9:0] load_tile_mm_Block_entry38_proc_U0_ap_return_1;
wire   [9:0] load_tile_mm_Block_entry38_proc_U0_ap_return_2;
wire   [8:0] load_tile_mm_Block_entry38_proc_U0_ap_return_3;
wire   [8:0] load_tile_mm_Block_entry38_proc_U0_ap_return_4;
wire    ap_channel_done_sext_ln43_3_loc_i_channel;
wire    sext_ln43_3_loc_i_channel_full_n;
reg    ap_sync_reg_channel_write_sext_ln43_3_loc_i_channel;
wire    ap_sync_channel_write_sext_ln43_3_loc_i_channel;
wire    ap_channel_done_sext_ln43_1_loc_i_channel;
wire    sext_ln43_1_loc_i_channel_full_n;
reg    ap_sync_reg_channel_write_sext_ln43_1_loc_i_channel;
wire    ap_sync_channel_write_sext_ln43_1_loc_i_channel;
wire    ap_channel_done_h0_cast10_loc_i_channel;
wire    h0_cast10_loc_i_channel_full_n;
reg    ap_sync_reg_channel_write_h0_cast10_loc_i_channel;
wire    ap_sync_channel_write_h0_cast10_loc_i_channel;
wire    ap_channel_done_w0_cast19_loc_i_channel;
wire    w0_cast19_loc_i_channel_full_n;
reg    ap_sync_reg_channel_write_w0_cast19_loc_i_channel;
wire    ap_sync_channel_write_w0_cast19_loc_i_channel;
wire    ap_channel_done_in_tile_0_offset_cast_loc_i_channel;
wire    in_tile_0_offset_cast_loc_i_channel_full_n;
reg    ap_sync_reg_channel_write_in_tile_0_offset_cast_loc_i_channel;
wire    ap_sync_channel_write_in_tile_0_offset_cast_loc_i_channel;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_ap_start;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_ap_done;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_ap_continue;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_ap_idle;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWVALID;
wire   [63:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWADDR;
wire   [0:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWID;
wire   [31:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWLEN;
wire   [2:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWSIZE;
wire   [1:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWBURST;
wire   [1:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWLOCK;
wire   [3:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWCACHE;
wire   [2:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWPROT;
wire   [3:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWQOS;
wire   [3:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWREGION;
wire   [0:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWUSER;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_WVALID;
wire   [31:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_WDATA;
wire   [3:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_WSTRB;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_WLAST;
wire   [0:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_WID;
wire   [0:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_WUSER;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARVALID;
wire   [63:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARADDR;
wire   [0:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARID;
wire   [31:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARLEN;
wire   [2:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARSIZE;
wire   [1:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARBURST;
wire   [1:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARLOCK;
wire   [3:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARCACHE;
wire   [2:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARPROT;
wire   [3:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARQOS;
wire   [3:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARREGION;
wire   [0:0] load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARUSER;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_RREADY;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_BREADY;
wire   [9:0] load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_address0;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_ce0;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_we0;
wire   [31:0] load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_d0;
wire   [9:0] load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_address0;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_ce0;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_we0;
wire   [31:0] load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_d0;
wire   [9:0] load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_address0;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_ce0;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_we0;
wire   [31:0] load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_d0;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_write;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_write;
wire    load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_write;
wire   [63:0] in_tile_0_offset_cast_loc_i_channel_dout;
wire   [1:0] in_tile_0_offset_cast_loc_i_channel_num_data_valid;
wire   [1:0] in_tile_0_offset_cast_loc_i_channel_fifo_cap;
wire    in_tile_0_offset_cast_loc_i_channel_empty_n;
wire   [9:0] w0_cast19_loc_i_channel_dout;
wire   [1:0] w0_cast19_loc_i_channel_num_data_valid;
wire   [1:0] w0_cast19_loc_i_channel_fifo_cap;
wire    w0_cast19_loc_i_channel_empty_n;
wire   [9:0] h0_cast10_loc_i_channel_dout;
wire   [1:0] h0_cast10_loc_i_channel_num_data_valid;
wire   [1:0] h0_cast10_loc_i_channel_fifo_cap;
wire    h0_cast10_loc_i_channel_empty_n;
wire   [8:0] sext_ln43_1_loc_i_channel_dout;
wire   [1:0] sext_ln43_1_loc_i_channel_num_data_valid;
wire   [1:0] sext_ln43_1_loc_i_channel_fifo_cap;
wire    sext_ln43_1_loc_i_channel_empty_n;
wire   [8:0] sext_ln43_3_loc_i_channel_dout;
wire   [1:0] sext_ln43_3_loc_i_channel_num_data_valid;
wire   [1:0] sext_ln43_3_loc_i_channel_fifo_cap;
wire    sext_ln43_3_loc_i_channel_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_load_tile_mm_Block_entry38_proc_U0_ap_ready;
wire    ap_sync_load_tile_mm_Block_entry38_proc_U0_ap_ready;
reg    ap_sync_reg_load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready;
wire    ap_sync_load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_sext_ln43_3_loc_i_channel = 1'b0;
#0 ap_sync_reg_channel_write_sext_ln43_1_loc_i_channel = 1'b0;
#0 ap_sync_reg_channel_write_h0_cast10_loc_i_channel = 1'b0;
#0 ap_sync_reg_channel_write_w0_cast19_loc_i_channel = 1'b0;
#0 ap_sync_reg_channel_write_in_tile_0_offset_cast_loc_i_channel = 1'b0;
#0 ap_sync_reg_load_tile_mm_Block_entry38_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready = 1'b0;
end

srcnn_load_tile_mm_Block_entry38_proc load_tile_mm_Block_entry38_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(load_tile_mm_Block_entry38_proc_U0_ap_start),
    .ap_done(load_tile_mm_Block_entry38_proc_U0_ap_done),
    .ap_continue(load_tile_mm_Block_entry38_proc_U0_ap_continue),
    .ap_idle(load_tile_mm_Block_entry38_proc_U0_ap_idle),
    .ap_ready(load_tile_mm_Block_entry38_proc_U0_ap_ready),
    .phase(phase),
    .w0(w0),
    .h0(h0),
    .h0_c1_din(load_tile_mm_Block_entry38_proc_U0_h0_c1_din),
    .h0_c1_num_data_valid(2'd0),
    .h0_c1_fifo_cap(2'd0),
    .h0_c1_full_n(h0_c1_full_n),
    .h0_c1_write(load_tile_mm_Block_entry38_proc_U0_h0_c1_write),
    .w0_c2_din(load_tile_mm_Block_entry38_proc_U0_w0_c2_din),
    .w0_c2_num_data_valid(2'd0),
    .w0_c2_fifo_cap(2'd0),
    .w0_c2_full_n(w0_c2_full_n),
    .w0_c2_write(load_tile_mm_Block_entry38_proc_U0_w0_c2_write),
    .phase_c3_din(load_tile_mm_Block_entry38_proc_U0_phase_c3_din),
    .phase_c3_num_data_valid(2'd0),
    .phase_c3_fifo_cap(2'd0),
    .phase_c3_full_n(phase_c3_full_n),
    .phase_c3_write(load_tile_mm_Block_entry38_proc_U0_phase_c3_write),
    .ap_return_0(load_tile_mm_Block_entry38_proc_U0_ap_return_0),
    .ap_return_1(load_tile_mm_Block_entry38_proc_U0_ap_return_1),
    .ap_return_2(load_tile_mm_Block_entry38_proc_U0_ap_return_2),
    .ap_return_3(load_tile_mm_Block_entry38_proc_U0_ap_return_3),
    .ap_return_4(load_tile_mm_Block_entry38_proc_U0_ap_return_4)
);

srcnn_load_tile_mm_Loop_InputTileHread_proc load_tile_mm_Loop_InputTileHread_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(load_tile_mm_Loop_InputTileHread_proc_U0_ap_start),
    .ap_done(load_tile_mm_Loop_InputTileHread_proc_U0_ap_done),
    .ap_continue(load_tile_mm_Loop_InputTileHread_proc_U0_ap_continue),
    .ap_idle(load_tile_mm_Loop_InputTileHread_proc_U0_ap_idle),
    .ap_ready(load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready),
    .p_read(in_tile_0_offset_cast_loc_i_channel_dout),
    .p_read1(sext_ln43_1_loc_i_channel_dout),
    .p_read2(sext_ln43_3_loc_i_channel_dout),
    .p_read3(h0_cast10_loc_i_channel_dout),
    .p_read4(w0_cast19_loc_i_channel_dout),
    .in_r(input_ftmap),
    .m_axi_gmem_in_AWVALID(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWVALID),
    .m_axi_gmem_in_AWREADY(1'b0),
    .m_axi_gmem_in_AWADDR(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWADDR),
    .m_axi_gmem_in_AWID(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWID),
    .m_axi_gmem_in_AWLEN(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWLEN),
    .m_axi_gmem_in_AWSIZE(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWSIZE),
    .m_axi_gmem_in_AWBURST(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWBURST),
    .m_axi_gmem_in_AWLOCK(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWLOCK),
    .m_axi_gmem_in_AWCACHE(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWCACHE),
    .m_axi_gmem_in_AWPROT(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWPROT),
    .m_axi_gmem_in_AWQOS(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWQOS),
    .m_axi_gmem_in_AWREGION(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWREGION),
    .m_axi_gmem_in_AWUSER(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_AWUSER),
    .m_axi_gmem_in_WVALID(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_WVALID),
    .m_axi_gmem_in_WREADY(1'b0),
    .m_axi_gmem_in_WDATA(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_WDATA),
    .m_axi_gmem_in_WSTRB(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_WSTRB),
    .m_axi_gmem_in_WLAST(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_WLAST),
    .m_axi_gmem_in_WID(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_WID),
    .m_axi_gmem_in_WUSER(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_WUSER),
    .m_axi_gmem_in_ARVALID(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARVALID),
    .m_axi_gmem_in_ARREADY(m_axi_gmem_in_ARREADY),
    .m_axi_gmem_in_ARADDR(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARADDR),
    .m_axi_gmem_in_ARID(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARID),
    .m_axi_gmem_in_ARLEN(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARLEN),
    .m_axi_gmem_in_ARSIZE(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARSIZE),
    .m_axi_gmem_in_ARBURST(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARBURST),
    .m_axi_gmem_in_ARLOCK(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARLOCK),
    .m_axi_gmem_in_ARCACHE(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARCACHE),
    .m_axi_gmem_in_ARPROT(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARPROT),
    .m_axi_gmem_in_ARQOS(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARQOS),
    .m_axi_gmem_in_ARREGION(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARREGION),
    .m_axi_gmem_in_ARUSER(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARUSER),
    .m_axi_gmem_in_RVALID(m_axi_gmem_in_RVALID),
    .m_axi_gmem_in_RREADY(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_RREADY),
    .m_axi_gmem_in_RDATA(m_axi_gmem_in_RDATA),
    .m_axi_gmem_in_RLAST(m_axi_gmem_in_RLAST),
    .m_axi_gmem_in_RID(m_axi_gmem_in_RID),
    .m_axi_gmem_in_RFIFONUM(m_axi_gmem_in_RFIFONUM),
    .m_axi_gmem_in_RUSER(m_axi_gmem_in_RUSER),
    .m_axi_gmem_in_RRESP(m_axi_gmem_in_RRESP),
    .m_axi_gmem_in_BVALID(1'b0),
    .m_axi_gmem_in_BREADY(load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_BREADY),
    .m_axi_gmem_in_BRESP(2'd0),
    .m_axi_gmem_in_BID(1'd0),
    .m_axi_gmem_in_BUSER(1'd0),
    .srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_address0(load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_address0),
    .srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_ce0(load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_ce0),
    .srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_we0(load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_we0),
    .srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_d0(load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_d0),
    .srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_address0(load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_address0),
    .srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_ce0(load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_ce0),
    .srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_we0(load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_we0),
    .srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_d0(load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_d0),
    .srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_address0(load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_address0),
    .srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_ce0(load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_ce0),
    .srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_we0(load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_we0),
    .srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_d0(load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_d0)
);

srcnn_fifo_w64_d2_S in_tile_0_offset_cast_loc_i_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_tile_mm_Block_entry38_proc_U0_ap_return_0),
    .if_full_n(in_tile_0_offset_cast_loc_i_channel_full_n),
    .if_write(ap_channel_done_in_tile_0_offset_cast_loc_i_channel),
    .if_dout(in_tile_0_offset_cast_loc_i_channel_dout),
    .if_num_data_valid(in_tile_0_offset_cast_loc_i_channel_num_data_valid),
    .if_fifo_cap(in_tile_0_offset_cast_loc_i_channel_fifo_cap),
    .if_empty_n(in_tile_0_offset_cast_loc_i_channel_empty_n),
    .if_read(load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready)
);

srcnn_fifo_w10_d2_S w0_cast19_loc_i_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_tile_mm_Block_entry38_proc_U0_ap_return_1),
    .if_full_n(w0_cast19_loc_i_channel_full_n),
    .if_write(ap_channel_done_w0_cast19_loc_i_channel),
    .if_dout(w0_cast19_loc_i_channel_dout),
    .if_num_data_valid(w0_cast19_loc_i_channel_num_data_valid),
    .if_fifo_cap(w0_cast19_loc_i_channel_fifo_cap),
    .if_empty_n(w0_cast19_loc_i_channel_empty_n),
    .if_read(load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready)
);

srcnn_fifo_w10_d2_S h0_cast10_loc_i_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_tile_mm_Block_entry38_proc_U0_ap_return_2),
    .if_full_n(h0_cast10_loc_i_channel_full_n),
    .if_write(ap_channel_done_h0_cast10_loc_i_channel),
    .if_dout(h0_cast10_loc_i_channel_dout),
    .if_num_data_valid(h0_cast10_loc_i_channel_num_data_valid),
    .if_fifo_cap(h0_cast10_loc_i_channel_fifo_cap),
    .if_empty_n(h0_cast10_loc_i_channel_empty_n),
    .if_read(load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready)
);

srcnn_fifo_w9_d2_S sext_ln43_1_loc_i_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_tile_mm_Block_entry38_proc_U0_ap_return_3),
    .if_full_n(sext_ln43_1_loc_i_channel_full_n),
    .if_write(ap_channel_done_sext_ln43_1_loc_i_channel),
    .if_dout(sext_ln43_1_loc_i_channel_dout),
    .if_num_data_valid(sext_ln43_1_loc_i_channel_num_data_valid),
    .if_fifo_cap(sext_ln43_1_loc_i_channel_fifo_cap),
    .if_empty_n(sext_ln43_1_loc_i_channel_empty_n),
    .if_read(load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready)
);

srcnn_fifo_w9_d2_S sext_ln43_3_loc_i_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_tile_mm_Block_entry38_proc_U0_ap_return_4),
    .if_full_n(sext_ln43_3_loc_i_channel_full_n),
    .if_write(ap_channel_done_sext_ln43_3_loc_i_channel),
    .if_dout(sext_ln43_3_loc_i_channel_dout),
    .if_num_data_valid(sext_ln43_3_loc_i_channel_num_data_valid),
    .if_fifo_cap(sext_ln43_3_loc_i_channel_fifo_cap),
    .if_empty_n(sext_ln43_3_loc_i_channel_empty_n),
    .if_read(load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_h0_cast10_loc_i_channel <= 1'b0;
    end else begin
        if (((load_tile_mm_Block_entry38_proc_U0_ap_done & load_tile_mm_Block_entry38_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_h0_cast10_loc_i_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_h0_cast10_loc_i_channel <= ap_sync_channel_write_h0_cast10_loc_i_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_in_tile_0_offset_cast_loc_i_channel <= 1'b0;
    end else begin
        if (((load_tile_mm_Block_entry38_proc_U0_ap_done & load_tile_mm_Block_entry38_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_in_tile_0_offset_cast_loc_i_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_in_tile_0_offset_cast_loc_i_channel <= ap_sync_channel_write_in_tile_0_offset_cast_loc_i_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_sext_ln43_1_loc_i_channel <= 1'b0;
    end else begin
        if (((load_tile_mm_Block_entry38_proc_U0_ap_done & load_tile_mm_Block_entry38_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_sext_ln43_1_loc_i_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_sext_ln43_1_loc_i_channel <= ap_sync_channel_write_sext_ln43_1_loc_i_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_sext_ln43_3_loc_i_channel <= 1'b0;
    end else begin
        if (((load_tile_mm_Block_entry38_proc_U0_ap_done & load_tile_mm_Block_entry38_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_sext_ln43_3_loc_i_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_sext_ln43_3_loc_i_channel <= ap_sync_channel_write_sext_ln43_3_loc_i_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_w0_cast19_loc_i_channel <= 1'b0;
    end else begin
        if (((load_tile_mm_Block_entry38_proc_U0_ap_done & load_tile_mm_Block_entry38_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_w0_cast19_loc_i_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_w0_cast19_loc_i_channel <= ap_sync_channel_write_w0_cast19_loc_i_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_load_tile_mm_Block_entry38_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_load_tile_mm_Block_entry38_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_load_tile_mm_Block_entry38_proc_U0_ap_ready <= ap_sync_load_tile_mm_Block_entry38_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready <= ap_sync_load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready;
        end
    end
end

assign ap_channel_done_h0_cast10_loc_i_channel = (load_tile_mm_Block_entry38_proc_U0_ap_done & (ap_sync_reg_channel_write_h0_cast10_loc_i_channel ^ 1'b1));

assign ap_channel_done_in_tile_0_offset_cast_loc_i_channel = (load_tile_mm_Block_entry38_proc_U0_ap_done & (ap_sync_reg_channel_write_in_tile_0_offset_cast_loc_i_channel ^ 1'b1));

assign ap_channel_done_sext_ln43_1_loc_i_channel = (load_tile_mm_Block_entry38_proc_U0_ap_done & (ap_sync_reg_channel_write_sext_ln43_1_loc_i_channel ^ 1'b1));

assign ap_channel_done_sext_ln43_3_loc_i_channel = (load_tile_mm_Block_entry38_proc_U0_ap_done & (ap_sync_reg_channel_write_sext_ln43_3_loc_i_channel ^ 1'b1));

assign ap_channel_done_w0_cast19_loc_i_channel = (load_tile_mm_Block_entry38_proc_U0_ap_done & (ap_sync_reg_channel_write_w0_cast19_loc_i_channel ^ 1'b1));

assign ap_done = load_tile_mm_Loop_InputTileHread_proc_U0_ap_done;

assign ap_idle = (load_tile_mm_Loop_InputTileHread_proc_U0_ap_idle & load_tile_mm_Block_entry38_proc_U0_ap_idle & (sext_ln43_3_loc_i_channel_empty_n ^ 1'b1) & (sext_ln43_1_loc_i_channel_empty_n ^ 1'b1) & (h0_cast10_loc_i_channel_empty_n ^ 1'b1) & (w0_cast19_loc_i_channel_empty_n ^ 1'b1) & (in_tile_0_offset_cast_loc_i_channel_empty_n ^ 1'b1));

assign ap_ready = ap_sync_ready;

assign ap_sync_channel_write_h0_cast10_loc_i_channel = ((h0_cast10_loc_i_channel_full_n & ap_channel_done_h0_cast10_loc_i_channel) | ap_sync_reg_channel_write_h0_cast10_loc_i_channel);

assign ap_sync_channel_write_in_tile_0_offset_cast_loc_i_channel = ((in_tile_0_offset_cast_loc_i_channel_full_n & ap_channel_done_in_tile_0_offset_cast_loc_i_channel) | ap_sync_reg_channel_write_in_tile_0_offset_cast_loc_i_channel);

assign ap_sync_channel_write_sext_ln43_1_loc_i_channel = ((sext_ln43_1_loc_i_channel_full_n & ap_channel_done_sext_ln43_1_loc_i_channel) | ap_sync_reg_channel_write_sext_ln43_1_loc_i_channel);

assign ap_sync_channel_write_sext_ln43_3_loc_i_channel = ((sext_ln43_3_loc_i_channel_full_n & ap_channel_done_sext_ln43_3_loc_i_channel) | ap_sync_reg_channel_write_sext_ln43_3_loc_i_channel);

assign ap_sync_channel_write_w0_cast19_loc_i_channel = ((w0_cast19_loc_i_channel_full_n & ap_channel_done_w0_cast19_loc_i_channel) | ap_sync_reg_channel_write_w0_cast19_loc_i_channel);

assign ap_sync_load_tile_mm_Block_entry38_proc_U0_ap_ready = (load_tile_mm_Block_entry38_proc_U0_ap_ready | ap_sync_reg_load_tile_mm_Block_entry38_proc_U0_ap_ready);

assign ap_sync_load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready = (load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready | ap_sync_reg_load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready & ap_sync_load_tile_mm_Block_entry38_proc_U0_ap_ready);

assign h0_c1_din = load_tile_mm_Block_entry38_proc_U0_h0_c1_din;

assign h0_c1_write = load_tile_mm_Block_entry38_proc_U0_h0_c1_write;

assign load_tile_mm_Block_entry38_proc_U0_ap_continue = (ap_sync_channel_write_w0_cast19_loc_i_channel & ap_sync_channel_write_sext_ln43_3_loc_i_channel & ap_sync_channel_write_sext_ln43_1_loc_i_channel & ap_sync_channel_write_in_tile_0_offset_cast_loc_i_channel & ap_sync_channel_write_h0_cast10_loc_i_channel);

assign load_tile_mm_Block_entry38_proc_U0_ap_start = ((ap_sync_reg_load_tile_mm_Block_entry38_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign load_tile_mm_Loop_InputTileHread_proc_U0_ap_continue = ap_continue;

assign load_tile_mm_Loop_InputTileHread_proc_U0_ap_start = (w0_cast19_loc_i_channel_empty_n & sext_ln43_3_loc_i_channel_empty_n & sext_ln43_1_loc_i_channel_empty_n & in_tile_0_offset_cast_loc_i_channel_empty_n & h0_cast10_loc_i_channel_empty_n & (ap_sync_reg_load_tile_mm_Loop_InputTileHread_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_write = 1'b0;

assign load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_write = 1'b0;

assign load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_write = 1'b0;

assign m_axi_gmem_in_ARADDR = load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARADDR;

assign m_axi_gmem_in_ARBURST = load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARBURST;

assign m_axi_gmem_in_ARCACHE = load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARCACHE;

assign m_axi_gmem_in_ARID = load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARID;

assign m_axi_gmem_in_ARLEN = load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARLEN;

assign m_axi_gmem_in_ARLOCK = load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARLOCK;

assign m_axi_gmem_in_ARPROT = load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARPROT;

assign m_axi_gmem_in_ARQOS = load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARQOS;

assign m_axi_gmem_in_ARREGION = load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARREGION;

assign m_axi_gmem_in_ARSIZE = load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARSIZE;

assign m_axi_gmem_in_ARUSER = load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARUSER;

assign m_axi_gmem_in_ARVALID = load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_ARVALID;

assign m_axi_gmem_in_AWADDR = 64'd0;

assign m_axi_gmem_in_AWBURST = 2'd0;

assign m_axi_gmem_in_AWCACHE = 4'd0;

assign m_axi_gmem_in_AWID = 1'd0;

assign m_axi_gmem_in_AWLEN = 32'd0;

assign m_axi_gmem_in_AWLOCK = 2'd0;

assign m_axi_gmem_in_AWPROT = 3'd0;

assign m_axi_gmem_in_AWQOS = 4'd0;

assign m_axi_gmem_in_AWREGION = 4'd0;

assign m_axi_gmem_in_AWSIZE = 3'd0;

assign m_axi_gmem_in_AWUSER = 1'd0;

assign m_axi_gmem_in_AWVALID = 1'b0;

assign m_axi_gmem_in_BREADY = 1'b0;

assign m_axi_gmem_in_RREADY = load_tile_mm_Loop_InputTileHread_proc_U0_m_axi_gmem_in_RREADY;

assign m_axi_gmem_in_WDATA = 32'd0;

assign m_axi_gmem_in_WID = 1'd0;

assign m_axi_gmem_in_WLAST = 1'b0;

assign m_axi_gmem_in_WSTRB = 4'd0;

assign m_axi_gmem_in_WUSER = 1'd0;

assign m_axi_gmem_in_WVALID = 1'b0;

assign phase_c3_din = load_tile_mm_Block_entry38_proc_U0_phase_c3_din;

assign phase_c3_write = load_tile_mm_Block_entry38_proc_U0_phase_c3_write;

assign srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_address0 = load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_address0;

assign srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_ce0 = load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_ce0;

assign srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_d0 = load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_d0;

assign srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_we0 = load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_we0;

assign srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_write = load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_11_write;

assign srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_address0 = load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_address0;

assign srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_ce0 = load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_ce0;

assign srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_d0 = load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_d0;

assign srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_we0 = load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_we0;

assign srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_write = load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_12_write;

assign srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_address0 = load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_address0;

assign srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_ce0 = load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_ce0;

assign srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_d0 = load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_d0;

assign srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_we0 = load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_we0;

assign srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_write = load_tile_mm_Loop_InputTileHread_proc_U0_srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_13_write;

assign w0_c2_din = load_tile_mm_Block_entry38_proc_U0_w0_c2_din;

assign w0_c2_write = load_tile_mm_Block_entry38_proc_U0_w0_c2_write;

endmodule //srcnn_load_tile_mm
