-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity srcnn_store_stream6 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_out_i_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    s_out_i_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    s_out_i_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    s_out_i_empty_n : IN STD_LOGIC;
    s_out_i_read : OUT STD_LOGIC;
    m_axi_gmem_out_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_out_AWREADY : IN STD_LOGIC;
    m_axi_gmem_out_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_out_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_out_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_WVALID : OUT STD_LOGIC;
    m_axi_gmem_out_WREADY : IN STD_LOGIC;
    m_axi_gmem_out_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_out_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_WLAST : OUT STD_LOGIC;
    m_axi_gmem_out_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_out_ARREADY : IN STD_LOGIC;
    m_axi_gmem_out_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_out_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_out_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_RVALID : IN STD_LOGIC;
    m_axi_gmem_out_RREADY : OUT STD_LOGIC;
    m_axi_gmem_out_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_out_RLAST : IN STD_LOGIC;
    m_axi_gmem_out_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_out_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_BVALID : IN STD_LOGIC;
    m_axi_gmem_out_BREADY : OUT STD_LOGIC;
    m_axi_gmem_out_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    output_ftmap_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    output_ftmap_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    output_ftmap_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    output_ftmap_empty_n : IN STD_LOGIC;
    output_ftmap_read : OUT STD_LOGIC;
    h0_dout : IN STD_LOGIC_VECTOR (8 downto 0);
    h0_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    h0_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    h0_empty_n : IN STD_LOGIC;
    h0_read : OUT STD_LOGIC;
    w0_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    w0_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    w0_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    w0_empty_n : IN STD_LOGIC;
    w0_read : OUT STD_LOGIC;
    tw_eff_loc_i_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    tw_eff_loc_i_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    tw_eff_loc_i_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    tw_eff_loc_i_empty_n : IN STD_LOGIC;
    tw_eff_loc_i_read : OUT STD_LOGIC );
end;


architecture behav of srcnn_store_stream6 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv9_10 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_10 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_FFFFFFE8 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111101000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv24_FFFFFF : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111111111111";
    constant ap_const_lv24_FFFFE8 : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111111101000";
    constant ap_const_lv32_FFFFFFE7 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111100111";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_7E : STD_LOGIC_VECTOR (7 downto 0) := "01111110";
    constant ap_const_lv8_E : STD_LOGIC_VECTOR (7 downto 0) := "00001110";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal s_out_i_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln416_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_out_blk_n_AW : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal gmem_out_blk_n_W : STD_LOGIC;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal gmem_out_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal output_ftmap_blk_n : STD_LOGIC;
    signal h0_blk_n : STD_LOGIC;
    signal w0_blk_n : STD_LOGIC;
    signal tw_eff_loc_i_blk_n : STD_LOGIC;
    signal out_reg_695 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal tw_eff_reg_700 : STD_LOGIC_VECTOR (7 downto 0);
    signal th_eff_fu_240_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal th_eff_reg_705 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln414_fu_248_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln414_reg_710 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln414_1_fu_260_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln414_1_reg_715 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln414_2_fu_264_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln414_2_reg_720 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln414_fu_285_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln414_reg_728 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal gmem_out_addr_reg_733 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln414_fu_280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln416_fu_369_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln416_reg_742 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state4 : BOOLEAN;
    signal s_out_i_read_reg_747 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_3_reg_753 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln417_fu_383_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal sub_ln417_reg_759 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln417_3_fu_680_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln417_3_reg_764 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal x_reg_205 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln416_fu_354_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal y_fu_156 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln609_fu_216_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln608_fu_230_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_222_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln609_fu_234_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_252_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln414_3_fu_276_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_fu_291_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl_i_fu_296_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_shl1_i_fu_308_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_shl_cast7_i_fu_304_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal p_shl1_cast8_i_fu_316_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal empty_83_fu_320_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal p_cast_fu_326_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_fu_330_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_cast_fu_335_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_84_fu_339_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln1_fu_344_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal select_ln417_fu_398_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_i_fu_403_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_1_i_fu_413_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln417_fu_421_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_i_fu_425_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln417_1_fu_433_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln417_fu_443_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_449_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln417_1_fu_465_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln417_4_fu_469_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln417_5_fu_475_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal lshr_ln417_2_fu_479_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal and_ln417_2_fu_485_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal icmp_ln417_1_fu_459_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln417_2_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_503_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln417_fu_439_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln417_1_fu_517_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal bit_select30_i_i_i_fu_523_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln417_fu_511_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln417_1_fu_531_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln417_fu_497_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln417_fu_537_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln417_2_fu_561_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln417_fu_551_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln417_1_fu_567_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln417_2_fu_577_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln417_2_fu_583_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln417_3_fu_555_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln417_fu_571_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln417_fu_587_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln_i_fu_543_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln417_1_fu_593_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln417_3_fu_601_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln417_3_fu_605_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal lshr_ln417_1_fu_611_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_6_fu_625_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln417_2_fu_641_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln417_3_fu_645_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln417_2_fu_633_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln417_4_fu_651_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln417_4_fu_621_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_5_i_fu_657_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pi_assign_fu_664_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln417_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal LD_fu_676_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln414_fu_280_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    x_reg_205_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((m_axi_gmem_out_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                x_reg_205 <= add_ln416_reg_742;
            elsif (((m_axi_gmem_out_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                x_reg_205 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    y_fu_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (tw_eff_loc_i_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (output_ftmap_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_156 <= ap_const_lv8_0;
            elsif ((not(((s_out_i_empty_n = ap_const_logic_0) and (icmp_ln416_fu_364_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln416_fu_364_p2 = ap_const_lv1_1))) then 
                y_fu_156 <= add_ln414_reg_728;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln414_reg_728 <= add_ln414_fu_285_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((s_out_i_empty_n = ap_const_logic_0) and (icmp_ln416_fu_364_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                add_ln416_reg_742 <= add_ln416_fu_369_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln414_fu_280_p2 = ap_const_lv1_0))) then
                gmem_out_addr_reg_733 <= sext_ln416_fu_354_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (tw_eff_loc_i_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (output_ftmap_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                out_reg_695 <= output_ftmap_dout;
                th_eff_reg_705 <= th_eff_fu_240_p3;
                tw_eff_reg_700 <= tw_eff_loc_i_dout;
                    zext_ln414_1_reg_715(9 downto 2) <= zext_ln414_1_fu_260_p1(9 downto 2);
                    zext_ln414_2_reg_720(7 downto 0) <= zext_ln414_2_fu_264_p1(7 downto 0);
                    zext_ln414_reg_710(8 downto 0) <= zext_ln414_fu_248_p1(8 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((s_out_i_empty_n = ap_const_logic_0) and (icmp_ln416_fu_364_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln416_fu_364_p2 = ap_const_lv1_0))) then
                s_out_i_read_reg_747 <= s_out_i_dout;
                sub_ln417_reg_759 <= sub_ln417_fu_383_p2;
                tmp_3_reg_753 <= s_out_i_dout(23 downto 23);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                select_ln417_3_reg_764 <= select_ln417_3_fu_680_p3;
            end if;
        end if;
    end process;
    zext_ln414_reg_710(9) <= '0';
    zext_ln414_1_reg_715(1 downto 0) <= "00";
    zext_ln414_1_reg_715(21 downto 10) <= "000000000000";
    zext_ln414_2_reg_720(31 downto 8) <= "000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, s_out_i_empty_n, m_axi_gmem_out_AWREADY, m_axi_gmem_out_WREADY, m_axi_gmem_out_BVALID, output_ftmap_empty_n, h0_empty_n, w0_empty_n, tw_eff_loc_i_empty_n, ap_CS_fsm_state4, icmp_ln416_fu_364_p2, ap_CS_fsm_state3, ap_CS_fsm_state6, ap_CS_fsm_state11, ap_CS_fsm_state2, icmp_ln414_fu_280_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (tw_eff_loc_i_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (output_ftmap_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln414_fu_280_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((m_axi_gmem_out_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if ((not(((s_out_i_empty_n = ap_const_logic_0) and (icmp_ln416_fu_364_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln416_fu_364_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                elsif ((not(((s_out_i_empty_n = ap_const_logic_0) and (icmp_ln416_fu_364_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln416_fu_364_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((m_axi_gmem_out_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((m_axi_gmem_out_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    LD_fu_676_p1 <= pi_assign_fu_664_p5(32 - 1 downto 0);
    add_ln414_fu_285_p2 <= std_logic_vector(unsigned(y_fu_156) + unsigned(ap_const_lv8_1));
    add_ln416_fu_369_p2 <= std_logic_vector(unsigned(x_reg_205) + unsigned(ap_const_lv8_1));
    add_ln417_1_fu_517_p2 <= std_logic_vector(unsigned(trunc_ln417_fu_439_p1) + unsigned(ap_const_lv24_FFFFE8));
    add_ln417_2_fu_561_p2 <= std_logic_vector(unsigned(sub_ln417_1_fu_433_p2) + unsigned(ap_const_lv32_FFFFFFE7));
    add_ln417_3_fu_605_p2 <= std_logic_vector(unsigned(select_ln417_1_fu_593_p3) + unsigned(zext_ln417_3_fu_601_p1));
    add_ln417_4_fu_651_p2 <= std_logic_vector(unsigned(sub_ln417_3_fu_645_p2) + unsigned(select_ln417_2_fu_633_p3));
    add_ln417_fu_443_p2 <= std_logic_vector(unsigned(sub_ln417_1_fu_433_p2) + unsigned(ap_const_lv32_FFFFFFE8));
    add_ln609_fu_216_p2 <= std_logic_vector(unsigned(h0_dout) + unsigned(ap_const_lv9_10));
    and_ln417_1_fu_531_p2 <= (xor_ln417_fu_511_p2 and bit_select30_i_i_i_fu_523_p3);
    and_ln417_2_fu_485_p2 <= (select_ln417_fu_398_p3 and lshr_ln417_2_fu_479_p2);
    and_ln417_fu_497_p2 <= (icmp_ln417_2_fu_491_p2 and icmp_ln417_1_fu_459_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state11_blk_assign_proc : process(m_axi_gmem_out_BVALID)
    begin
        if ((m_axi_gmem_out_BVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg, output_ftmap_empty_n, h0_empty_n, w0_empty_n, tw_eff_loc_i_empty_n)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (tw_eff_loc_i_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (output_ftmap_empty_n = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(m_axi_gmem_out_AWREADY)
    begin
        if ((m_axi_gmem_out_AWREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(s_out_i_empty_n, icmp_ln416_fu_364_p2)
    begin
        if (((s_out_i_empty_n = ap_const_logic_0) and (icmp_ln416_fu_364_p2 = ap_const_lv1_0))) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(m_axi_gmem_out_WREADY)
    begin
        if ((m_axi_gmem_out_WREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, output_ftmap_empty_n, h0_empty_n, w0_empty_n, tw_eff_loc_i_empty_n)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (tw_eff_loc_i_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (output_ftmap_empty_n = ap_const_logic_0));
    end process;


    ap_block_state4_assign_proc : process(s_out_i_empty_n, icmp_ln416_fu_364_p2)
    begin
                ap_block_state4 <= ((s_out_i_empty_n = ap_const_logic_0) and (icmp_ln416_fu_364_p2 = ap_const_lv1_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln414_fu_280_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln414_fu_280_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln414_fu_280_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln414_fu_280_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bit_select30_i_i_i_fu_523_p3 <= select_ln417_fu_398_p3(to_integer(unsigned(add_ln417_1_fu_517_p2)) downto to_integer(unsigned(add_ln417_1_fu_517_p2))) when (to_integer(unsigned(add_ln417_1_fu_517_p2)) >= 0 and to_integer(unsigned(add_ln417_1_fu_517_p2)) <=23) else "-";
    empty_83_fu_320_p2 <= std_logic_vector(unsigned(p_shl_cast7_i_fu_304_p1) - unsigned(p_shl1_cast8_i_fu_316_p1));
    empty_84_fu_339_p2 <= std_logic_vector(signed(tmp_cast_fu_335_p1) + signed(out_reg_695));
    empty_fu_291_p2 <= std_logic_vector(unsigned(zext_ln414_reg_710) + unsigned(zext_ln414_3_fu_276_p1));

    gmem_out_blk_n_AW_assign_proc : process(m_axi_gmem_out_AWREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            gmem_out_blk_n_AW <= m_axi_gmem_out_AWREADY;
        else 
            gmem_out_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem_out_blk_n_B_assign_proc : process(m_axi_gmem_out_BVALID, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            gmem_out_blk_n_B <= m_axi_gmem_out_BVALID;
        else 
            gmem_out_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    gmem_out_blk_n_W_assign_proc : process(m_axi_gmem_out_WREADY, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            gmem_out_blk_n_W <= m_axi_gmem_out_WREADY;
        else 
            gmem_out_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;


    h0_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, h0_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            h0_blk_n <= h0_empty_n;
        else 
            h0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    h0_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, output_ftmap_empty_n, h0_empty_n, w0_empty_n, tw_eff_loc_i_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (tw_eff_loc_i_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (output_ftmap_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            h0_read <= ap_const_logic_1;
        else 
            h0_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln414_fu_280_p2 <= "1" when (y_fu_156 = th_eff_reg_705) else "0";
    icmp_ln416_fu_364_p2 <= "1" when (x_reg_205 = tw_eff_reg_700) else "0";
    icmp_ln417_1_fu_459_p2 <= "1" when (signed(tmp_4_fu_449_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln417_2_fu_491_p2 <= "0" when (and_ln417_2_fu_485_p2 = ap_const_lv24_0) else "1";
    icmp_ln417_3_fu_555_p2 <= "1" when (signed(add_ln417_fu_443_p2) > signed(ap_const_lv32_0)) else "0";
    icmp_ln417_fu_393_p2 <= "1" when (s_out_i_read_reg_747 = ap_const_lv24_0) else "0";
    lshr_ln417_1_fu_611_p4 <= add_ln417_3_fu_605_p2(63 downto 1);
    lshr_ln417_2_fu_479_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv24_FFFFFF),to_integer(unsigned('0' & zext_ln417_5_fu_475_p1(24-1 downto 0)))));
    lshr_ln417_fu_571_p2 <= std_logic_vector(shift_right(unsigned(zext_ln417_fu_551_p1),to_integer(unsigned('0' & zext_ln417_1_fu_567_p1(31-1 downto 0)))));
    m_axi_gmem_out_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_out_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_out_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_out_ARID <= ap_const_lv1_0;
    m_axi_gmem_out_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_out_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_out_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_out_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_out_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_out_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_out_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_out_ARVALID <= ap_const_logic_0;
    m_axi_gmem_out_AWADDR <= gmem_out_addr_reg_733;
    m_axi_gmem_out_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_out_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_out_AWID <= ap_const_lv1_0;
    m_axi_gmem_out_AWLEN <= zext_ln414_2_reg_720;
    m_axi_gmem_out_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_out_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_out_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_out_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_out_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_out_AWUSER <= ap_const_lv1_0;

    m_axi_gmem_out_AWVALID_assign_proc : process(m_axi_gmem_out_AWREADY, ap_CS_fsm_state3)
    begin
        if (((m_axi_gmem_out_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem_out_AWVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_out_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem_out_BREADY_assign_proc : process(m_axi_gmem_out_BVALID, ap_CS_fsm_state11)
    begin
        if (((m_axi_gmem_out_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            m_axi_gmem_out_BREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_out_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_out_RREADY <= ap_const_logic_0;
    m_axi_gmem_out_WDATA <= select_ln417_3_reg_764;
    m_axi_gmem_out_WID <= ap_const_lv1_0;
    m_axi_gmem_out_WLAST <= ap_const_logic_0;
    m_axi_gmem_out_WSTRB <= ap_const_lv4_F;
    m_axi_gmem_out_WUSER <= ap_const_lv1_0;

    m_axi_gmem_out_WVALID_assign_proc : process(m_axi_gmem_out_WREADY, ap_CS_fsm_state6)
    begin
        if (((m_axi_gmem_out_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            m_axi_gmem_out_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_out_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    or_ln417_fu_537_p2 <= (and_ln417_fu_497_p2 or and_ln417_1_fu_531_p2);
    or_ln_i_fu_543_p3 <= (ap_const_lv1_0 & or_ln417_fu_537_p2);

    output_ftmap_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, output_ftmap_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            output_ftmap_blk_n <= output_ftmap_empty_n;
        else 
            output_ftmap_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    output_ftmap_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, output_ftmap_empty_n, h0_empty_n, w0_empty_n, tw_eff_loc_i_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (tw_eff_loc_i_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (output_ftmap_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            output_ftmap_read <= ap_const_logic_1;
        else 
            output_ftmap_read <= ap_const_logic_0;
        end if; 
    end process;

        p_cast_fu_326_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_83_fu_320_p2),22));

    p_shl1_cast8_i_fu_316_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl1_i_fu_308_p3),21));
    p_shl1_i_fu_308_p3 <= (empty_fu_291_p2 & ap_const_lv2_0);
    p_shl_cast7_i_fu_304_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl_i_fu_296_p3),21));
    p_shl_i_fu_296_p3 <= (empty_fu_291_p2 & ap_const_lv10_0);
    pi_assign_fu_664_p5 <= (zext_ln417_4_fu_621_p1(63 downto 32) & tmp_5_i_fu_657_p3 & zext_ln417_4_fu_621_p1(22 downto 0));

    s_out_i_blk_n_assign_proc : process(s_out_i_empty_n, ap_CS_fsm_state4, icmp_ln416_fu_364_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln416_fu_364_p2 = ap_const_lv1_0))) then 
            s_out_i_blk_n <= s_out_i_empty_n;
        else 
            s_out_i_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_out_i_read_assign_proc : process(s_out_i_empty_n, ap_CS_fsm_state4, icmp_ln416_fu_364_p2)
    begin
        if ((not(((s_out_i_empty_n = ap_const_logic_0) and (icmp_ln416_fu_364_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln416_fu_364_p2 = ap_const_lv1_0))) then 
            s_out_i_read <= ap_const_logic_1;
        else 
            s_out_i_read <= ap_const_logic_0;
        end if; 
    end process;

    select_ln417_1_fu_593_p3 <= 
        lshr_ln417_fu_571_p2 when (icmp_ln417_3_fu_555_p2(0) = '1') else 
        shl_ln417_fu_587_p2;
    select_ln417_2_fu_633_p3 <= 
        ap_const_lv8_7F when (tmp_6_fu_625_p3(0) = '1') else 
        ap_const_lv8_7E;
    select_ln417_3_fu_680_p3 <= 
        ap_const_lv32_0 when (icmp_ln417_fu_393_p2(0) = '1') else 
        LD_fu_676_p1;
    select_ln417_fu_398_p3 <= 
        sub_ln417_reg_759 when (tmp_3_reg_753(0) = '1') else 
        s_out_i_read_reg_747;
        sext_ln416_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_fu_344_p4),64));

        sext_ln417_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_i_fu_413_p3),32));

    shl_ln417_fu_587_p2 <= std_logic_vector(shift_left(unsigned(zext_ln417_fu_551_p1),to_integer(unsigned('0' & zext_ln417_2_fu_583_p1(31-1 downto 0)))));
    sub_ln417_1_fu_433_p2 <= std_logic_vector(unsigned(ap_const_lv32_18) - unsigned(tmp_2_i_fu_425_p3));
    sub_ln417_2_fu_577_p2 <= std_logic_vector(unsigned(ap_const_lv32_19) - unsigned(sub_ln417_1_fu_433_p2));
    sub_ln417_3_fu_645_p2 <= std_logic_vector(unsigned(ap_const_lv8_E) - unsigned(trunc_ln417_2_fu_641_p1));
    sub_ln417_4_fu_469_p2 <= std_logic_vector(signed(ap_const_lv5_11) - signed(trunc_ln417_1_fu_465_p1));
    sub_ln417_fu_383_p2 <= std_logic_vector(unsigned(ap_const_lv24_0) - unsigned(s_out_i_dout));
    th_eff_fu_240_p3 <= 
        xor_ln609_fu_234_p2 when (tmp_2_fu_222_p3(0) = '1') else 
        ap_const_lv8_10;
    tmp_1_fu_252_p3 <= (w0_dout & ap_const_lv2_0);
    tmp_1_i_fu_413_p3 <= (ap_const_lv1_1 & tmp_i_fu_403_p4);
    tmp_2_fu_222_p3 <= add_ln609_fu_216_p2(8 downto 8);
    
    tmp_2_i_fu_425_p3_proc : process(sext_ln417_fu_421_p1)
    begin
        tmp_2_i_fu_425_p3 <= std_logic_vector(to_unsigned(32, 32));
        for i in 0 to 32 - 1 loop
            if sext_ln417_fu_421_p1(i) = '1' then
                tmp_2_i_fu_425_p3 <= std_logic_vector(to_unsigned(i,32));
                exit;
            end if;
        end loop;
    end process;

    tmp_4_fu_449_p4 <= add_ln417_fu_443_p2(31 downto 1);
    tmp_5_fu_503_p3 <= add_ln417_fu_443_p2(31 downto 31);
    tmp_5_i_fu_657_p3 <= (tmp_3_reg_753 & add_ln417_4_fu_651_p2);
    tmp_6_fu_625_p3 <= add_ln417_3_fu_605_p2(25 downto 25);
        tmp_cast_fu_335_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_330_p2),64));

    tmp_fu_330_p2 <= std_logic_vector(signed(p_cast_fu_326_p1) + signed(zext_ln414_1_reg_715));
    
    tmp_i_fu_403_p4_proc : process(select_ln417_fu_398_p3)
    variable vlo_cpy : STD_LOGIC_VECTOR(24+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(24+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(24 - 1 downto 0);
    variable tmp_i_fu_403_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(24 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(24 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(24 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_17(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        v0_cpy := select_ln417_fu_398_p3;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(24-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(24-1-unsigned(ap_const_lv32_17(5-1 downto 0)));
            for tmp_i_fu_403_p4_i in 0 to 24-1 loop
                v0_cpy(tmp_i_fu_403_p4_i) := select_ln417_fu_398_p3(24-1-tmp_i_fu_403_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(24-1 downto 0)))));
        res_mask := res_mask(24-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_i_fu_403_p4 <= resvalue(24-1 downto 0);
    end process;

    trunc_ln1_fu_344_p4 <= empty_84_fu_339_p2(63 downto 2);
    trunc_ln417_1_fu_465_p1 <= sub_ln417_1_fu_433_p2(5 - 1 downto 0);
    trunc_ln417_2_fu_641_p1 <= tmp_2_i_fu_425_p3(8 - 1 downto 0);
    trunc_ln417_fu_439_p1 <= sub_ln417_1_fu_433_p2(24 - 1 downto 0);
    trunc_ln608_fu_230_p1 <= h0_dout(8 - 1 downto 0);

    tw_eff_loc_i_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, tw_eff_loc_i_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            tw_eff_loc_i_blk_n <= tw_eff_loc_i_empty_n;
        else 
            tw_eff_loc_i_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    tw_eff_loc_i_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, output_ftmap_empty_n, h0_empty_n, w0_empty_n, tw_eff_loc_i_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (tw_eff_loc_i_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (output_ftmap_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            tw_eff_loc_i_read <= ap_const_logic_1;
        else 
            tw_eff_loc_i_read <= ap_const_logic_0;
        end if; 
    end process;


    w0_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, w0_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w0_blk_n <= w0_empty_n;
        else 
            w0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    w0_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, output_ftmap_empty_n, h0_empty_n, w0_empty_n, tw_eff_loc_i_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (tw_eff_loc_i_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (output_ftmap_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w0_read <= ap_const_logic_1;
        else 
            w0_read <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln417_fu_511_p2 <= (tmp_5_fu_503_p3 xor ap_const_lv1_1);
    xor_ln609_fu_234_p2 <= (trunc_ln608_fu_230_p1 xor ap_const_lv8_FF);
    zext_ln414_1_fu_260_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_252_p3),22));
    zext_ln414_2_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tw_eff_loc_i_dout),32));
    zext_ln414_3_fu_276_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_fu_156),10));
    zext_ln414_fu_248_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(h0_dout),10));
    zext_ln417_1_fu_567_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln417_2_fu_561_p2),64));
    zext_ln417_2_fu_583_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln417_2_fu_577_p2),64));
    zext_ln417_3_fu_601_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_i_fu_543_p3),64));
    zext_ln417_4_fu_621_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln417_1_fu_611_p4),64));
    zext_ln417_5_fu_475_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln417_4_fu_469_p2),24));
    zext_ln417_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln417_fu_398_p3),64));
end behav;
