-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity srcnn_compute_tile_Block_entry87_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    phase_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    phase_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    phase_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    phase_empty_n : IN STD_LOGIC;
    phase_read : OUT STD_LOGIC;
    w0_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    w0_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    w0_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    w0_empty_n : IN STD_LOGIC;
    w0_read : OUT STD_LOGIC;
    h0_dout : IN STD_LOGIC_VECTOR (8 downto 0);
    h0_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    h0_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    h0_empty_n : IN STD_LOGIC;
    h0_read : OUT STD_LOGIC;
    h0_c_din : OUT STD_LOGIC_VECTOR (8 downto 0);
    h0_c_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    h0_c_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    h0_c_full_n : IN STD_LOGIC;
    h0_c_write : OUT STD_LOGIC;
    w0_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    w0_c_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    w0_c_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    w0_c_full_n : IN STD_LOGIC;
    w0_c_write : OUT STD_LOGIC;
    phase_c_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    phase_c_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    phase_c_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    phase_c_full_n : IN STD_LOGIC;
    phase_c_write : OUT STD_LOGIC;
    srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_14 : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (10 downto 0) );
end;


architecture behav of srcnn_compute_tile_Block_entry87_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv9_10 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_10 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_const_lv9_2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal phase_blk_n : STD_LOGIC;
    signal w0_blk_n : STD_LOGIC;
    signal h0_blk_n : STD_LOGIC;
    signal h0_c_blk_n : STD_LOGIC;
    signal w0_c_blk_n : STD_LOGIC;
    signal phase_c_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal trunc_ln531_cast_fu_100_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln532_fu_110_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_116_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln532_fu_124_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln529_fu_138_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln528_fu_152_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_27_fu_144_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln529_fu_156_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln538_fu_104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln532_fu_130_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln529_fu_162_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal th_eff_cast_loc_i_i_0_fu_182_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln110_fu_186_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tw_eff_cast_loc_i_i_0_fu_178_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln110_1_fu_196_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_tile_offset_cast_loc_i_i_0_fu_170_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal in_tile_0_offset_cast_loc_i_i_0_fu_174_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln110_fu_192_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln110_1_fu_202_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln110_2_fu_210_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln110_3_fu_214_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_return_0_preg : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_return_1_preg : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_return_2_preg : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal ap_return_3_preg : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal ap_return_4_preg : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal ap_return_5_preg : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal ap_return_6_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_return_7_preg : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal ap_return_8_preg : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg(0) <= '0';
            else
                if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        ap_return_0_preg(0) <= out_tile_offset_cast_loc_i_i_0_fu_170_p1(0);
                end if; 
            end if;
        end if;
    end process;


    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg(0) <= '0';
            else
                if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        ap_return_1_preg(0) <= in_tile_0_offset_cast_loc_i_i_0_fu_174_p1(0);
                end if; 
            end if;
        end if;
    end process;


    ap_return_2_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_2_preg(0) <= '0';
                ap_return_2_preg(1) <= '0';
                ap_return_2_preg(2) <= '0';
                ap_return_2_preg(3) <= '0';
                ap_return_2_preg(4) <= '0';
                ap_return_2_preg(5) <= '0';
                ap_return_2_preg(6) <= '0';
                ap_return_2_preg(7) <= '0';
            else
                if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        ap_return_2_preg(7 downto 0) <= tw_eff_cast_loc_i_i_0_fu_178_p1(7 downto 0);
                end if; 
            end if;
        end if;
    end process;


    ap_return_3_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_3_preg(0) <= '0';
                ap_return_3_preg(1) <= '0';
                ap_return_3_preg(2) <= '0';
                ap_return_3_preg(3) <= '0';
                ap_return_3_preg(4) <= '0';
                ap_return_3_preg(5) <= '0';
                ap_return_3_preg(6) <= '0';
                ap_return_3_preg(7) <= '0';
            else
                if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        ap_return_3_preg(7 downto 0) <= th_eff_cast_loc_i_i_0_fu_182_p1(7 downto 0);
                end if; 
            end if;
        end if;
    end process;


    ap_return_4_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_4_preg(0) <= '0';
                ap_return_4_preg(1) <= '0';
                ap_return_4_preg(2) <= '0';
                ap_return_4_preg(3) <= '0';
                ap_return_4_preg(4) <= '0';
                ap_return_4_preg(5) <= '0';
                ap_return_4_preg(6) <= '0';
                ap_return_4_preg(7) <= '0';
                ap_return_4_preg(8) <= '0';
            else
                if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        ap_return_4_preg(8 downto 0) <= zext_ln110_fu_192_p1(8 downto 0);
                end if; 
            end if;
        end if;
    end process;


    ap_return_5_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_5_preg(0) <= '0';
                ap_return_5_preg(1) <= '0';
                ap_return_5_preg(2) <= '0';
                ap_return_5_preg(3) <= '0';
                ap_return_5_preg(4) <= '0';
                ap_return_5_preg(5) <= '0';
                ap_return_5_preg(6) <= '0';
                ap_return_5_preg(7) <= '0';
                ap_return_5_preg(8) <= '0';
            else
                if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        ap_return_5_preg(8 downto 0) <= zext_ln110_1_fu_202_p1(8 downto 0);
                end if; 
            end if;
        end if;
    end process;


    ap_return_6_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_6_preg <= ap_const_lv32_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_6_preg <= srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_14;
                end if; 
            end if;
        end if;
    end process;


    ap_return_7_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_7_preg(0) <= '0';
                ap_return_7_preg(1) <= '0';
                ap_return_7_preg(2) <= '0';
                ap_return_7_preg(3) <= '0';
                ap_return_7_preg(4) <= '0';
                ap_return_7_preg(5) <= '0';
                ap_return_7_preg(6) <= '0';
                ap_return_7_preg(7) <= '0';
            else
                if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        ap_return_7_preg(7 downto 0) <= zext_ln110_2_fu_210_p1(7 downto 0);
                end if; 
            end if;
        end if;
    end process;


    ap_return_8_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_8_preg(0) <= '0';
                ap_return_8_preg(1) <= '0';
                ap_return_8_preg(2) <= '0';
                ap_return_8_preg(3) <= '0';
                ap_return_8_preg(4) <= '0';
                ap_return_8_preg(5) <= '0';
                ap_return_8_preg(6) <= '0';
                ap_return_8_preg(7) <= '0';
                ap_return_8_preg(8) <= '0';
            else
                if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        ap_return_8_preg(8 downto 0) <= zext_ln110_3_fu_214_p1(8 downto 0);
                end if; 
            end if;
        end if;
    end process;

    ap_return_0_preg(63 downto 1) <= "000000000000000000000000000000000000000000000000000000000000000";
    ap_return_1_preg(63 downto 1) <= "000000000000000000000000000000000000000000000000000000000000000";
    ap_return_2_preg(8) <= '0';
    ap_return_3_preg(8) <= '0';
    ap_return_4_preg(9) <= '0';
    ap_return_5_preg(9) <= '0';
    ap_return_7_preg(9 downto 8) <= "00";
    ap_return_8_preg(10 downto 9) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln110_1_fu_196_p2 <= std_logic_vector(unsigned(tw_eff_cast_loc_i_i_0_fu_178_p1) + unsigned(ap_const_lv9_2));
    add_ln110_fu_186_p2 <= std_logic_vector(unsigned(th_eff_cast_loc_i_i_0_fu_182_p1) + unsigned(ap_const_lv9_2));
    add_ln529_fu_138_p2 <= std_logic_vector(unsigned(h0_dout) + unsigned(ap_const_lv9_10));
    add_ln532_fu_110_p2 <= std_logic_vector(unsigned(trunc_ln531_cast_fu_100_p1) + unsigned(ap_const_lv9_10));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n)
    begin
        if (((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n, out_tile_offset_cast_loc_i_i_0_fu_170_p1, ap_return_0_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_0 <= out_tile_offset_cast_loc_i_i_0_fu_170_p1;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    ap_return_1_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n, in_tile_0_offset_cast_loc_i_i_0_fu_174_p1, ap_return_1_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_1 <= in_tile_0_offset_cast_loc_i_i_0_fu_174_p1;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;


    ap_return_2_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n, tw_eff_cast_loc_i_i_0_fu_178_p1, ap_return_2_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_2 <= tw_eff_cast_loc_i_i_0_fu_178_p1;
        else 
            ap_return_2 <= ap_return_2_preg;
        end if; 
    end process;


    ap_return_3_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n, th_eff_cast_loc_i_i_0_fu_182_p1, ap_return_3_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_3 <= th_eff_cast_loc_i_i_0_fu_182_p1;
        else 
            ap_return_3 <= ap_return_3_preg;
        end if; 
    end process;


    ap_return_4_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n, zext_ln110_fu_192_p1, ap_return_4_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_4 <= zext_ln110_fu_192_p1;
        else 
            ap_return_4 <= ap_return_4_preg;
        end if; 
    end process;


    ap_return_5_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n, zext_ln110_1_fu_202_p1, ap_return_5_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_5 <= zext_ln110_1_fu_202_p1;
        else 
            ap_return_5 <= ap_return_5_preg;
        end if; 
    end process;


    ap_return_6_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n, srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_14, ap_return_6_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_6 <= srcnn_float_255_255_float_1_9_9_float_float_64_1_1_f_14;
        else 
            ap_return_6 <= ap_return_6_preg;
        end if; 
    end process;


    ap_return_7_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n, zext_ln110_2_fu_210_p1, ap_return_7_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_7 <= zext_ln110_2_fu_210_p1;
        else 
            ap_return_7 <= ap_return_7_preg;
        end if; 
    end process;


    ap_return_8_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n, zext_ln110_3_fu_214_p1, ap_return_8_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_8 <= zext_ln110_3_fu_214_p1;
        else 
            ap_return_8 <= ap_return_8_preg;
        end if; 
    end process;


    h0_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, h0_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            h0_blk_n <= h0_empty_n;
        else 
            h0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    h0_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, h0_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            h0_c_blk_n <= h0_c_full_n;
        else 
            h0_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    h0_c_din <= h0_dout;

    h0_c_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            h0_c_write <= ap_const_logic_1;
        else 
            h0_c_write <= ap_const_logic_0;
        end if; 
    end process;


    h0_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            h0_read <= ap_const_logic_1;
        else 
            h0_read <= ap_const_logic_0;
        end if; 
    end process;

    in_tile_0_offset_cast_loc_i_i_0_fu_174_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(phase_dout),64));
    out_tile_offset_cast_loc_i_i_0_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln538_fu_104_p2),64));

    phase_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            phase_blk_n <= phase_empty_n;
        else 
            phase_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    phase_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            phase_c_blk_n <= phase_c_full_n;
        else 
            phase_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    phase_c_din <= phase_dout;

    phase_c_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            phase_c_write <= ap_const_logic_1;
        else 
            phase_c_write <= ap_const_logic_0;
        end if; 
    end process;


    phase_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            phase_read <= ap_const_logic_1;
        else 
            phase_read <= ap_const_logic_0;
        end if; 
    end process;

    select_ln529_fu_162_p3 <= 
        xor_ln529_fu_156_p2 when (tmp_27_fu_144_p3(0) = '1') else 
        ap_const_lv8_10;
    select_ln532_fu_130_p3 <= 
        xor_ln532_fu_124_p2 when (tmp_fu_116_p3(0) = '1') else 
        ap_const_lv8_10;
    th_eff_cast_loc_i_i_0_fu_182_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln529_fu_162_p3),9));
    tmp_27_fu_144_p3 <= add_ln529_fu_138_p2(8 downto 8);
    tmp_fu_116_p3 <= add_ln532_fu_110_p2(8 downto 8);
    trunc_ln528_fu_152_p1 <= h0_dout(8 - 1 downto 0);
    trunc_ln531_cast_fu_100_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(w0_dout),9));
    tw_eff_cast_loc_i_i_0_fu_178_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln532_fu_130_p3),9));

    w0_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, w0_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w0_blk_n <= w0_empty_n;
        else 
            w0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    w0_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, w0_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w0_c_blk_n <= w0_c_full_n;
        else 
            w0_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    w0_c_din <= w0_dout;

    w0_c_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w0_c_write <= ap_const_logic_1;
        else 
            w0_c_write <= ap_const_logic_0;
        end if; 
    end process;


    w0_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, phase_empty_n, w0_empty_n, h0_empty_n, h0_c_full_n, w0_c_full_n, phase_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (phase_c_full_n = ap_const_logic_0) or (w0_c_full_n = ap_const_logic_0) or (h0_c_full_n = ap_const_logic_0) or (h0_empty_n = ap_const_logic_0) or (w0_empty_n = ap_const_logic_0) or (phase_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w0_read <= ap_const_logic_1;
        else 
            w0_read <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln529_fu_156_p2 <= (trunc_ln528_fu_152_p1 xor ap_const_lv8_FF);
    xor_ln532_fu_124_p2 <= (w0_dout xor ap_const_lv8_FF);
    xor_ln538_fu_104_p2 <= (phase_dout xor ap_const_lv1_1);
    zext_ln110_1_fu_202_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln110_1_fu_196_p2),10));
    zext_ln110_2_fu_210_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(w0_dout),10));
    zext_ln110_3_fu_214_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(h0_dout),11));
    zext_ln110_fu_192_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln110_fu_186_p2),10));
end behav;
